### ISSUE TITLE
lib not in npm package

### ISSUE THREAD

**Issue by SamJacobs** [brendanmorrell/eslint-plugin-styled-components-a11y#14] opened 2021-01-26 16:25 UTC
Howdy, 
When I install this using `yarn` and then configure it and run lint, I get the following output:
```
Oops! Something went wrong! :(

ESLint: 7.15.0

ESLint couldn't find the plugin "eslint-plugin-styled-components-a11y".

(The package "eslint-plugin-styled-components-a11y" was not found when loaded as a Node module from the directory "/Users/sjacobs/Repos/carvanamarketplace".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-styled-components-a11y@latest --save-dev

The plugin "eslint-plugin-styled-components-a11y" was referenced from the config file in ".eslintrc.json".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

Looking at the installed package, all I see is 
![image](https://user-images.githubusercontent.com/2328488/105873088-bc278c00-5fc0-11eb-91a5-dca4f4286e8d.png)

I don't think I'm doing anything incorrectly, but if I am let me know.

**Comment by brendanmorrell** [comment] 2021-01-27 18:58
That doesn't immediately appear to be something related to this eslint
plugin specifically, although I could be wrong.

This is kind of a boilerplate answer, so maybe you've already done this,
but this looks like it might just be an npm/yarn hiccup since it is saying
it can't find it and it looks like it is in your node modules. I'd try
deleting node modules, making sure you don't have a package-lock.json since
you are using yarn (if you do, delete it), remove this plugin from your
package json (both dev and regular dependencies if you ahve it installed
twice), and then try running `yarn add -D
eslint-plugin-styled-components-a11y` and then `yarn` to reinstall all your
packages. Hopefully that allows it to correct itself and find the package.
If not, is this a public repo that I could take a look at? if not, I would
need a reproducible example probably to troubleshoot. What version of node
and eslint are you using, and is eslint installed locally or globally on
your machine?

**Comment by SamJacobs** [comment] 2021-01-27 19:08
I think the problem is that perhaps the last time you published you did not build your `lib` directory because it is missing from npm. Since that's where the entry point to the plugin lives, I'm guessing that's why it won't run

**Comment by selarom-epilef** [comment] 2021-01-27 19:18
I'm having the same issue `Failed to load plugin 'styled-components-a11y' declared in '.eslintrc.json'`

**Comment by brendanmorrell** [comment] 2021-01-28 02:03
Whoa. That would be a very big problem. Downloads have dropped significantly in the past month. I assumed it was just a holiday lull. Man. Thanks for pointing that out. Looking now

**Comment by brendanmorrell** [comment] 2021-01-28 02:16
Well, that is no beuno. Thank you for pointing that out. Honestly, the past two months the downloads have dropped like 65%, so I probably should have realized something was going on. Kind of surprised you are the first two to bring this up. Regardless, should be working now on the latest version. Thanks for pointing it out @SamJacobs  and @selarom-epilef . Let me know if you still run into issues.

**Comment by selarom-epilef** [comment] 2021-01-28 11:11
Tested `0.0.28` and it works fine now. Thanks for the quick fix @brendanmorrell !

**Comment by brendanmorrell** [comment] 2021-01-28 19:19
Excellent @selarom-epilef . Closing the issue. Thanks again!

**Closed by brendanmorrell** 2021-01-28 19:19 UTC
