### ISSUE TITLE
Cannot read property 'name' error

### ISSUE THREAD

**Issue by caraclarke** [brendanmorrell/eslint-plugin-styled-components-a11y#6] opened 2020-05-14 18:45 UTC
Hello, I am testing out this library in my project repo and am getting the below eror

<img width="1644" alt="Screen Shot 2020-05-14 at 2 39 49 PM" src="https://user-images.githubusercontent.com/12741704/81972898-4c6b9f80-95f1-11ea-9d7f-b9744956b458.png">

I added the library as directed to plugins

```
...
plugins: [
    'prettier',
    'react',
    'jsx-a11y',
    'styled-components-a11y',
...
  ],
...
```

and enabled the recommended rules
```
 extends: ['airbnb', 'prettier', 'plugin:styled-components-a11y/recommended'],
```

The line it seems to be failing on 
```
const StyledAlert = styled(Alert)`
  padding: 0 15px 15px 15px;
`;
```

Does this library only work with styled-components? My project runs emotion v9.2.4

react v16.13.0

**Comment by vanderhoop** [comment] 2020-05-18 16:52
We're seeing a similar error, and we're working _with_ styled components.

```
TypeError: Cannot read property 'name' of undefined
Occurred while linting /Users/travis.vanderhoop/dev/jupiter/packages/@ecomm/pg-careers/department-page/PageView.tsx:169
    at TaggedTemplateExpression (/Users/travis.vanderhoop/dev/jupiter/node_modules/eslint-plugin-styled-components-a11y/src/utils/collectStyledComponentData.js:33:47)
    at /Users/travis.vanderhoop/dev/jupiter/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/travis.vanderhoop/dev/jupiter/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/travis.vanderhoop/dev/jupiter/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/travis.vanderhoop/dev/jupiter/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/travis.vanderhoop/dev/jupiter/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/travis.vanderhoop/dev/jupiter/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
    at /Users/travis.vanderhoop/dev/jupiter/node_modules/eslint/lib/linter/linter.js:936:32
    at Array.forEach (<anonymous>)
```

**Comment by vanderhoop** [comment] 2020-05-18 17:51
__Update to the above:__ the error referenced above seems local to specific components. For example, we can scope the execution of the linter to other `*.tsx` files and identify accessibility issues in them just fine.

Going to fork the repo and investigate.

**Comment by brendanmorrell** [comment] 2020-05-26 18:44
Interesting. @caraclarke, is this happening uniformly (e.g., if you just try and lint some other file, does the error occur, or is it just happening when this file gets linted)? Also, could I get the full code sampkle that creates the error (like, the whole file if the Alert component is in that file, or the file plus whatever file Alert is defined in if it is imported)? @vanderhoop , could I also get the code causing the error for you?

**Comment by brendanmorrell** [comment] 2020-05-26 18:45
And @caraclarke, it should work fine with emotion. All that matters is the syntax needs to be the same.

**Comment by brendanmorrell** [comment] 2020-05-26 18:54
As a temporary solution before looking at the code, I would imagine pasting this on line 33 of src/utils/collectStyledComponentsData.js will remove the error:
```
        tag = node.tag.callee?.object?.property?.name;
        if (!tag) return;
```
It will stop the linter from being able to collect data on the component producing the error, but it will at least allow all of the other components to be linted until we get a solution/look at the offending code.  

Thanks!

**Comment by caraclarke** [comment] 2020-05-27 12:55
> Sorry for the delay. Was in the middle of a move, and just catching up on things.
> 
> Interesting. @caraclarke, is this happening uniformly (e.g., if you just try and lint some other file, does the error occur, or is it just happening when this file gets linted)?

@brendanmorrell It seems to be an issue in any file with this syntax where I wrap another component to add additional styles, something like:
```
import Alert from '../alert/alert.js';
const MoreStyles = styled(Alert)`
    color: red;
`;
```

where the `Alert` in `Alert.js` might have some styling like:
```
const StyledDialog = styled.div`
... styles that make a dialog
`;

export class Alert extends Component {
    render() {
      return <StyledDialog {...someProps} />
    }
}
```

When I try your suggested fix I get this error
```
const isAttrs = ({ tag }) => tag.callee?.property?.name === 'attrs';
                                        ^

SyntaxError: Unexpected token .
```

**Comment by brendanmorrell** [comment] 2020-05-27 23:28
@caraclarke It's possible I removed optional-chaining as a babel option since I don't use it anywhere in the project (outside of the suggested change I gave you), thus the unexpected token error. My apologies. I can add that back in, test your example, and make sure the fix works. I'll also try to get a full fix up within the next few days. 
I would imagine the issue is that the styled component is wrapped in the class component as opposed to Alert just being something like this:
```
export const Alert = styled(StyledDialog)``;
```
which is not something I ever do, and thus not something I remembered to test for.

Thanks for pointing out the issue and providing the example. I'll get back to you when I have next steps.

Thank again!

**Comment by bever1337** [comment] 2020-05-28 03:06
We make heavy use of styling components like in the Alert example above. One use case is extending the styles on a component, e.g. needing to add a margin to a highly-reused button but only in one place. Having support for that is essential for us. I just implemented this dependency into our app and am already excited with the results, and am otherwise very pleased. Thanks!

**Comment by caraclarke** [comment] 2020-05-28 19:41
So interesting update, I just discovered if I have jsx-a11y installed and enabled in my eslintrc and I install this library, without doing anything else I start getting jsx-a11y warnings on styled components including the kind that I was getting an error on before

**Comment by brendanmorrell** [comment] 2020-05-28 19:46
Alright. that is interesting. I was actually just going to say that I was unable to reproduce your issue.

**Comment by caraclarke** [comment] 2020-05-28 19:48
Yeah maybe there was something else broken in my config before? But yeah very interesting. I'm not familiar enough with how npm packages work to be sure of why its happening though it is good for my project since we can find more issues

**Comment by brendanmorrell** [comment] 2020-05-28 19:54
Yeah. I'll play around with it a little bit to see if I can reproduce it by tweaking the config and making sure jsx-a11y isn't installed to see if I can reproduce your issue. Out of curiosity, is this a private repo/do you have anything I could use as a baseline to reproduce the issue?

**Comment by brendanmorrell** [comment] 2020-05-28 19:59
Also, @vanderhoop and @bever1337: I republished the library with the optional chaining I had mentioned in the above comments. That may at least stop the error, although it will not lint those components if it is not actually capturing the data correctly (which the error indicates it isn't). As I mentioned above to @caraclarke, I actually was not able to reproduce the error she noted, so I was curious if I could get a codesandbox, a working repo where the error occurs, or at least a code sample which triggers the error so I could look into it. Is that a possibility?

Once again, thanks for letting me know of these issues so I can be aware/improve on the library, and keep me posted on any other issues/feature requests or missing listing situations you find. Thanks!

**Comment by caraclarke** [comment] 2020-05-28 20:00
My main repo is, yes but I have duplicated the scenario in this test repo: https://github.com/caraclarke/react-axe-linter-test, branch `a11y-error-example`

**Comment by brendanmorrell** [comment] 2020-05-28 20:06
Great. I'll play around with that then. I don't feel like you should need to install jsx-a11y independently for this plugin to work, so something to look into regardless. Thanks!

**Comment by caraclarke** [comment] 2020-05-28 20:07
> Yeah. I'll play around with it a little bit to see if I can reproduce it by tweaking the config and making sure jsx-a11y isn't installed to see if I can reproduce your issue. Out of curiosity, is this a private repo/do you have anything I could use as a baseline to reproduce the issue?

Also just as a note when I ran into this issue `jsx-a11y` was still installed in my repo and listed under plugins in my `package.json`

**Comment by vanderhoop** [comment] 2020-06-07 01:20
Hey @brendanmorrell, sorry for the delayed response. Finally got around to digging back into this. 

### `.attrs()`
The following component threw an error that I was able to avoid by stripping `.attrs({ bearing: 'left' })` from the code snippet below, so I suspect there are issues with handling [styled-components' `.attrs()`](https://styled-components.com/docs/api#attrs) API


Breaks with `TypeError: Cannot read property 'name' of undefined`
```es6
const LeftArrow = styled(DarkNavigationButton).attrs({ bearing: 'left' })`
  ${arrowStyles}
  left: -5px !important;
`;
```

Works:

```es6
const LeftArrow = styled(DarkNavigationButton)`
  ${arrowStyles}
  left: -5px !important;
`;
```

**Comment by vanderhoop** [comment] 2020-06-07 01:40
Note that the arguments passed to `.attrs()` could feasibly have accessibility implications, as they are merged into the props of the underlying styled component.

**Comment by brendanmorrell** [comment] 2020-06-07 20:16
Got it. Yes, I think I missed this combination (adding attrs not just to
something like styled.div but to a styled(Component) call), so the parser
is gonna crash on those. I appreciate the example. I'll take a look in the
next few days and see if I can get a fix up. I'll let you know when I
publish the new version

Thanks again

**Comment by brendanmorrell** [comment] 2020-07-15 06:43
done

**Closed by brendanmorrell** 2020-07-15 06:43 UTC

**Comment by brendanmorrell** [comment] 2020-07-18 22:32
Believe I fixed the issue with chaining .attrs on a call to styled with a
component parameter. Update to 0.0.16 and you should be good.
